### ISSUE TITLE
AVX2 port

### ISSUE THREAD

**Issue by simplejackcoder** [dpayne/loglogbeta#1]
AVX-512 is quite recent how hard is it port to AVX2?

**Comment by simplejackcoder** [comment]
Also @dnbaker's https://github.com/dnbaker/sketch/blob/main/include/sketch/hll.h is ~2000 lines and yours is 200. What is so simple now you implement newer paper?

**Comment by simplejackcoder** [comment]
Looks like there is one more out there that is simple. https://github.com/mindis/hll

**Comment by dpayne** [comment]
I believe both use a different algo, it mostly has to do with how the two algos handle error correction. If you are concerned about lines of code, mine can be reduced by a lot by removing the loop unrolling but at a small cost to performance.

As for AVX2, I did write a version with that but it wasn't dramatically improved over the base line non-avx version. After dumping the assembly I found that the compiler does a pretty decent job of swapping in avx2 instructions in the "non-avx" version when compiling with the avx2 compilation flags. Because of this I didn't think it was worth it to commit the avx2 version.

**Comment by dnbaker** [comment]
Commenting on this, the code I'm working with is designed for the Ertl new estimation algorithms, which uses vectors of counts instead of directly calculating the harmonic mean as loglogbeta does. The version in this repo (loglogbeta) likely scales faster. Also, the code from the sketch library has a mixture of variants of the HLL, which explains a lot of the size of the file.

**Comment by dpayne** [comment]
I ended up doing an implementation of the Ertl algos in a branch. The cardinality check was significantly faster but adding each hash was slower, so it ended up causing a significant slow down. I'll look to see if I can simply or speed up the add hash code for ertl and see if I can improve it, but for now I think the Ertl algos only make sense if you're repeatedly querying the cardinality, which I'm not doing for my use case.

```------------------------------------------------------------
Benchmark                  Time             CPU   Iterations
------------------------------------------------------------
AddHashErtl             7.47 ns         7.46 ns     94963085
CardinalityErtl         57.8 ns         57.8 ns     12532021
FullTestErtl          854322 ns       853805 ns          833
AddHash                 2.33 ns         2.33 ns    336815539
Cardinality             1634 ns         1633 ns       429464
CardinalityNonAvx      14968 ns        14958 ns        46771
FullTest              198086 ns       197922 ns         3531
FullTestNonAvx        199072 ns       198701 ns         3537```
